global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_from: alertmanager@example.com
  smtp_hello: localhost
  smtp_smarthost: smtp.example.com:587
  smtp_auth_username: ghanshyamramole999@gmail.com
  smtp_auth_password: <secret>
  smtp_require_tls: true
  smtp_tls_config:
    insecure_skip_verify: false
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  telegram_api_url: https://api.telegram.org
  webex_api_url: https://webexapis.com/v1/messages
  rocketchat_api_url: https://open.rocket.chat/
route:
  receiver: default-receiver
  group_by:
  - alertname
  continue: false
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
inhibit_rules:
- source_matchers:
  - severity="critical"
  target_matchers:
  - severity="warning"
  equal:
  - alertname
  - instance
receivers:
- name: default-receiver
  email_configs:
  - send_resolved: true
    to: ghanshyamramole.com
    from: alertmanager@example.com
    hello: localhost
    smarthost: smtp.example.com:587
    auth_username: ghanshyamramole999@gmail.com
    auth_password: <secret>
    headers:
      From: alertmanager@example.com
      Subject: '{{ template "email.default.subject" . }}'
      To: ghanshyamramole.com
    html: '{{ template "email.default.html" . }}'
    require_tls: true
    tls_config:
      insecure_skip_verify: false
templates: []
